#resp
mapping_document_resp = {
        'ird_id': 'ird_id',
        'ird_ic_id': 'ird_ic_id',
        'MessageType': 'ird_message_type',
        'ird_created_date': 'ird_created_date',
        'ird_filename' : 'ird_filename',
        'ReferenceNumber': 'ird_reference_number',
        'RegistrationID': 'ird_registration_id',
        'DocumentDetail_DeclarationAccept_DeclarationNumber' : 'ird_declaration_number',
        # 'rs_id'	: 'ird_rs_id',
        # 'rs_status_priority' : 'ird_rs_status_priority'
}

mapping_detail_resp = {
        'irt_id' : 'irt_id', 
        'irt_ird_id': 'irt_ird_id',
        'GoodsAudit_DeclarationNumber' : 'irt_goodsAudit_declaration_number', 
        'DeclarationReject_ItemNumber' : 'irt_declaration_reject_item_number',
        'GoodsTransitionAccept_GoodsTransitionNumber':'irt_goodstransition_accept_goodstransitionnumber',
        'GoodsTransitionAccept_ContainerNumber': 'irt_goodstransition_accept_containernumber',
        'GoodsTransitionAccept_LoadPort': 'irt_goodstransition_accept_loadport',

        'DeclarationAccept_Status': 'irt_declaration_accept_status',
        'DeclarationAccept_DeclarationNumber': 'irt_declaration_number', 
        'DeclarationAccept_TotalTax' : 'irt_declaration_accept_totaltax',
        'DeclarationAccept_TotalDeposit' : 'irt_declaration_accept_totaldeposit', 
        'DeclarationAccept_ReleasePort': 'irt_declarationaccept_release_port',
        'ShortDeclarationAccept_DeclarationNumber' : 'irt_short_declaration_accept_declarationnumber',
        'CancelDocumentAccept_DocumentNumber' : 'irt_cancel_documentd_accept_documentnumber', 

        'DeclarationPayment_Status' : 'irt_declaration_payment_status',
        'DeclarationPayment_PaymentType' : 'irt_declaration_payment_payment_type', 
        'DeclarationPayment_PaymentNumber' : 'irt_declaration_payment_payment_number',
        'DeclarationPayment_BankTransactionNumber' : 'irt_declaration_payment_bank_transaction_number',
        'DeclarationPayment_TotalAmount': 'irt_declaration_payment_total_amount',
        'GoodsTransitionReject_DeclarationNumber': 'irt_goodstransition_reject_declarationnumber',
        'GoodsTransitionReject_ContainerNumber': 'irt_goodstransition_reject_containernumber',

        'CancelDocumentReject_DocumentNumber' :'irt_cancel_documentr_eject_documentnumber',
        'ShortDeclarationReject_DeclarationNumber' : 'irt_short_declaration_reject_declarationnumber',
        'ShortDeclarationReject_DeclarationLineNumber' : 'irt_short_declaration_reject_declaration_linenumber',
        'ManifestAccept_ReceivedControlNumber' : 'irt_manifest_accept_received_controlnumber', 
        'ManifestAccept_PortCode' : 'irt_manifest_accept_portcode',
        'ManifestAccept_DocumentNumber' : 'irt_manifest_accept_documentnumber',
        'GoodsAudit_ContainerNumber' : 'irt_goods_audit_containernumber',
        'GoodsAudit_LoadPort' : 'irt_goodsaudit_loadport',
        'GoodsAudit_AuditDateTime' : 'irt_goodsaudit_audit_datetime', 
        'irt_message': 'irt_message',
        'irt_errorcode' : 'irt_errorcode',
        
        'ManifestReject_ReceivedControlNumber': 'irt_manifestreject_received_controlnumber',
        'ManifestReject_PortCode' : 'irt_manifestreject_portcode', 
        'ManifestReject_DocumentNumber' : 'irt_manifestreject_documentnumber',
        'ManifestReject_ItemNumber' :'irt_manifestreject_itemnumber',
    
        'GoodsTransitionReect_ContainerNumber' : 'irt_goodstransitionRreect_containernumber'
}

#---------------------------------------------------------------------------------------------------------------------
#cancel
mapping_cancel = {

        'ReferenceNumber' : 'cc_reference_number',
    	'DeclarationType' : 'cc_declaration_type',
        'CompanyInfo_TaxNumber' : 'cc_company_info_taxnumber',
    	'CompanyInfo_Branch' : 'cc_company_info_Branch',
        'Agent_TaxNumber' : 'cc_agent_taxnumber',
        'Agent_Branch'	: 'cc_agent_branch',
        'DocumentNumber' : 'cc_document_number',
        'CancelReason'	 : 'cc_cancel_reason',
        'RegistrationID' :	'cc_registration_id',
        'cc_filename':	'cc_filename',
        'cc_id': 'cc_id'
}
#---------------------------------------------------------------------------------------------------------------------
column_mapping = {
    'doc_id': 'ic_id',
    'ReferenceNumber': 'ic_referencenumber',
    'DocumentType': 'ic_documenttype',
    'Importer_TaxNumber': 'ic_importer_taxnumber',
    'Importer_Branch': 'ic_importer_branch',
    'Importer_ThaiName': 'ic_importer_thainame',
    'Importer_EnglishName': 'ic_importer_englishname',
    'Importer_StreetAndNumber': 'ic_importer_streetandnumber',
    'Importer_District': 'ic_importer_district',
    'Importer_SubProvince': 'ic_importer_subprovince',
    'Importer_Province': 'ic_importer_province',
    'Importer_Postcode': 'ic_importer_postcode',
    'Agent_TaxNumber': 'ic_agent_taxnumber',
    'Agent_Branch': 'ic_agent_branch',
    'AuthorisedPerson_CustomsClearanceIDCard': 'ic_authorisedperson_customsclearanceidcard',
    'AuthorisedPerson_CustomsClearanceName': 'ic_authorisedperson_customsclearancename',
    'AuthorisedPerson_ManagerIDCard': 'ic_authorisedperson_manageridcard',
    'AuthorisedPerson_ManagerName': 'ic_authorisedperson_managername',
    'BorderTransportMeans_ModeCode': 'ic_bordertransportmeans_modecode',
    'BorderTransportMeans_CargoTypeCode': 'ic_bordertransportmeans_cargotypecode',
    'BorderTransportMeans_VesselName': 'ic_bordertransportmeans_vesselname',
    'BorderTransportMeans_ArrivalDate': 'ic_bordertransportmeans_arrivaldate',
    'BillofLading_Master': 'ic_billoflading_master',
    'BillofLading_House': 'ic_billoflading_house',
    'OutsideReleasePort': 'ic_outside_release_port',
    'ReleasePort': 'ic_releaseport',
    'DischargePort': 'ic_dischargeport',
    'OriginCountryCode': 'ic_origincountrycode',
    'ConsignmentCountryCode': 'ic_consignmentcountrycode',
    'TotalPackage_ShippingMarks': 'ic_totalpackage_shippingmarks',
    'TotalPackage_Amount': 'ic_totalpackage_amount',
    'TotalPackage_UnitCode': 'ic_totalpackage_unitcode',
    'TotalNetWeight_Weight': 'ic_totalnetweight_weight',
    'TotalNetWeight_UnitCode': 'ic_totalnetweight_unitcode',
    'TotalGrossWeight_Weight': 'ic_totalgrossweight_weight',
    'TotalGrossWeight_UnitCode': 'ic_totalgrossweight_unitcode',
    'CurrencyCode': 'ic_currencycode',
    'RateofExchange': 'ic_rateofexchange',
    'CIFValue_Foreign': 'ic_cifvalue_foreign',
    'CIFValue_Baht': 'ic_cifvalue_baht',
    'RGSCode': 'ic_rgs_code',
    'BankInfo_CustomsBankCode': 'ic_bankinfo_customsbankcode',
    'BankInfo_BankCode': 'ic_bankinfo_bankcode',
    'BankInfo_BankBranchCode': 'ic_bankinfo_bankbranchcode',
    'BankInfo_AccountNumber': 'ic_bankinfo_accountnumber',
    'BankInfo_TotalPaymentAmount': 'ic_bankinfo_paymentmethod',
    'BankInfo_PaymentMethod': 'ic_payment_method',
    'TotalTax': 'ic_totaltax',
    'TotalDeposit': 'ic_totaldeposit',
    'CommonAccessReferenceNumber': 'ic_referencenumber_common_access',
    'AssessmentRequestCode': 'ic_assessment_request_code',
    'InspectionRequestCode': 'ic_inspection_request_code',
    'DepartureDate': 'ic_departure_date',
    'Approval_Port': 'ic_approval_port',
    'Approval_Number': 'ic_approval_number',
    'ObligationGuarantee_Method': 'ic_obligationguarantee_method',
    'ObligationGuarantee_Type': 'ic_guarantee_type',
    'ObligationGuarantee_BankCode': 'ic_guarantee_bank_code',
    'ObligationGuarantee_BankBranchCode': 'ic_guarantee_bank_branch_code',
    'ObligationGuarantee_AccountNumber': 'ic_guarantee_bank_account_number',
    'ObligationGuarantee_TotalAmount': 'ic_total_deposit_amount',
    'ExportTaxIncentivesID': 'ic_export_tax_incentives_id',
    'TradingPartner_TaxNumber': 'ic_company_trading_taxnumber',
    'TradingPartner_Branch': 'ic_company_trading_branch',
    'SubBrokerTaxNumber': 'ic_sub_broker_taxnumber',
    'DeferredDutyTaxFee': 'ic_deferred_payment_duty/tax/fee',
    'TaxCardInfo_BankCode': 'ic_tax_card_bank_code',
    'TaxCardInfo_BankBranchCode': 'ic_tax_card_bank_branch_code',
    'TaxCardInfo_AccountNumber': 'ic_tax_card_bank_account_number',
    'TaxCardInfo_TotalAmount': 'ic_total_tax_card_payment_amount',
    'RegistrationID': 'ic_registrationid'
}

mapping_invoice = {
    'Number': 'ii_invoice_number',
    'Date': 'ii_invoice_date',
    'PurchaseOrderNumber': 'ii_purchase_order_number',
    'TermofPaymentCode': 'ii_term_of_payment_code',
    'TradeTerms': 'ii_trade_terms',
    'ConsignorInfo_Status': 'ii_consignor_status',
    'CommercialLevel': 'ii_commercial_level',
    'ConsignorInfo_Name': 'ii_consignor_name',
    'ConsignorInfo_StreetAndNumber': 'ii_street_and_number',
    'ConsignorInfo_District': 'ii_district',
    'ConsignorInfo_SubProvince': 'ii_sub_province',
    'ConsignorInfo_Province': 'ii_province',
    'ConsignorInfo_Postcode': 'ii_postcode',
    'ConsignorInfo_CountryCode': 'ii_country_code',
    'ConsignorInfo_Email': 'ii_email',
    'CurrencyCode': 'ii_currency_code',
    'TotalAmount': 'ii_total_amount',
    'BuyerStatus': 'ii_buyer_status',
    'ForwardingCharge_CurrencyCode': 'ii_forwarding_charge_currency_code',
    'ForwardingCharge_Amount': 'ii_forwarding_charge_foreign',
    'Freight_CurrencyCode': 'ii_freight_currency_code',
    'Freight_Amount': 'ii_freight_amount_foreign',
    'Insurance_CurrencyCode': 'ii_insurance_currency_code',
    'Insurance_Amount': 'ii_insurance_amount_foreign',
    'PackingCharge_CurrencyCode': 'ii_packingcharge_currency_cod',
    'PackingCharge_Amount': 'ii_packingcharge_amount_foreign',
    'OtherCharge_CurrencyCode': 'ii_chargeamount_foreign_currency_code',
    'OtherCharge_Amount': 'ii_chargeamount_foreign',
    'LandingChargeCurrencyCode': 'ii_landingcharge_currency_cod',
    'OtherCharge_OtherChargeDescription': 'ii_detail_of_other_ch',
    'SelfCertificateRemark': 'ii_self_certification_remark',
    'AEOsReferenceNumber': 'ii_aeos_reference_number',
    'InteriorTransport_CurrencyCode': 'ii_interior_transport_currency_code',
    'InteriorTransport_Amount': 'ii_interior_transport_amount'
}

mapping_detail = {
    'ItemNumber': 'ide_itemnumber',
    'Invoice_Number': 'ide_invoice_number',
    'Invoice_Item': 'ide_invoice_item',
    'TariffInfo_Code': 'ide_tariffinfo_code',
    'TariffInfo_Sequence': 'ide_tariffinfo_sequence',
    'TariffInfo_Statistical': 'ide_tariffinfo_statistical',
    'PrivilegeCode': 'ide_privilegecode',
    'NatureofTransaction': 'ide_natureoftransaction',
    'ProductCode': 'ide_productcode',
    'GoodsDescription_Thai': 'ide_goodsdescription_thai',
    'GoodsDescription_English': 'ide_goodsdescription_english',
    'ProductInfo_Year': 'ide_productinfo_year',
    'ProductInfo_BrandName': 'ide_productinfo_brandname',
    'ProductInfo_OriginCountryCode': 'ide_productinfo_origincountrycode',
    'ProductInfo_NetWeight_Weight': 'ide_productinfo_netweight_weight',
    'ProductInfo_NetWeight_UnitCode': 'ide_productinfo_netweight_unitcode',
    'ProductInfo_Quantity_Quantity': 'ide_productinfo_quantity',
    'ProductInfo_Quantity_UnitCode': 'ide_productinfo_quantity_unitcode',
    'ProductInfo_CurrencyCode': 'ide_productinfo_currencycode',
    'ProductInfo_ExchangeRate': 'ide_productinfo_exchangerate',
    'ProductInfo_UnitPrice_Foreign': 'ide_productinfo_unitprice_foreign',
    'ProductInfo_UnitPrice_Baht': 'ide_productinfo_unitprice_baht',
    'ProductInfo_InvoiceQuantity_Quantity': 'ide_productinfo_invoicequantity_quantity',
    'ProductInfo_InvoiceQuantity_UnitCode': 'ide_productinfo_invoicequantity_unitcode',
    'ProductInfo_InvoiceAmount_Foreign': 'ide_productinfo_invoiceamount_foreign',
    'ProductInfo_InvoiceAmount_Baht': 'ide_productinfo_invoiceamount_baht',
    'ProductInfo_CIFValue_Foreign': 'ide_productinfo_cifvalue_foreign',
    'ProductInfo_CIFValue_Baht': 'ide_productinfo_cifvalue_baht',
    'ProductInfo_ShippingMarks': 'ide_productinfo_shippingmarks',
    'ReImportationCertificate': 'ide_reimportation_certificate',
    'BOI': 'ide_boi',
    'Bond': 'ide_bond',
    'Bis19': 'ide_bis19',
    'ReExport': 'ide_reexport',
    'FZ': 'ide_fz',
    'IEAT': 'ide_ieat',
    'Serveral': 'ide_serveral',
    'LastEntry': 'ide_lastentry',
    'ProductInfo_Package_Amount': 'ide_productinfo_package_amount',
    'ProductInfo_Package_UnitCode': 'ide_productinfo_package_unitcode',
    'ImportTaxIncentivesID': 'ide_import_tax_incentives_id',
    'OriginCriteria': 'ide_origincriteria',
    'ProductInfo_CustomsCode': 'ide_customs_product_code',
    'ProductInfo_Remark': 'ide_productinfo_remark',
    'ReferenceDeclaration_Number': 'ide_reference_declaration_number',
    'ReferenceDeclaration_LineNumber': 'ide_reference_declaration_line_number',
    'BOILicenseNumber': 'ide_boilicensenumber',
    'ExciseCode': 'ide_excise_code',
    'ExciseQuantity_Quantity': 'ide_excise_quantity',
    'ExciseQuantity_UnitCode': 'ide_excise_quantity_unit_code',
    'ExciseQuantity_AssessQuantity': 'ide_assess_quantity',
    'DeductedAmount': 'ide_deducted_amount',
    'ProductInfo_Attribute1': 'ide_product_attribute_1',
    'ProductInfo_Attribute2': 'ide_product_attribute_2',
    'TariffInfo_ImportTariff': 'ide_import_tariff',
    'ArgumentativeTariff_Code': 'ide_argumentative_tariff_code',
    'ArgumentativeTariff_Sequence': 'ide_argumentative_tariff_sequence',
    'ArgumentativeTariff_PrivilegeCode': 'ide_argumentative_privilege_code',
    'ArgumentativeTariff_ReasonCode': 'ide_argumentative_reason_code',
    'Duty_Argumentative_ValueRate': 'ide_argumentative_tariff_code',
    'Duty_Argumentative_SpecificRate': 'ide_argumentative_tariff_code',
    'ProductInfo_IncreasedPrice_Foreign': 'ide_productinfo_increasedprice_foreign',
    'ProductInfo_IncreasedPrice_Baht': 'ide_productinfo_increasedprice_baht',
    'ProductInfo_CIFValue_Assess': 'ide_productinfo_cifvalue_assess',
    'Duty_Amount_Deposit': 'ide_duty_deposit_amount',
    'Duty_Deposit_ReasonCode': 'ide_duty_deposit_reason_code',
    'Duty_Deposit_Amount': 'ide_duty_deposit_amount',
    'CertifiedExporterNumber': 'ide_certified_exporter_number',
    'UNDGNumber': 'ide_undg_number',
    'ModelInfo_Number': 'ide_model_number',
    'ModelInfo_Version': 'ide_model_version',
    'ModelInfo_CompanyTaxNumber': 'ide_model_company_tax_number',
    'Royalty': 'ide_royalty',
    'RoyaltyDetail': 'ide_detail_of_royalty'
}

mapping_duty = {
    'Type': 'idu_type',
    'Rate_Value': 'idu_rate_value',
    'Rate_Specific': 'idu_rate_specific',
    'Amount_Amount': 'idu_amount_amount',
    'Amount_Paid': 'idu_amount_paid',
    'Rate_Exemption': 'idu_rate_exemption',
    'Rate_SpecificUnitCode': 'idu_specific_unit_code',
    'Argumentative_ValueRate': 'idu_argumentative_value_rate',
    'Argumentative_SpecificRate': 'idu_argumentative_specific_rate',
    'Amount_Deposit': 'idu_deposit_amount'
}

mapping_permit = {
    'Number' : 'ip_number',
    'IssueInfo_Date' : 'ip_issue_date',
    'IssueInfo_Authority' : 'ip_issue_authority'
}
